"""
app/core/config_parts - 配置与基础设施子模块包
"""
from .env_config import (
    PROJECT_ROOT,
    DEFAULT_LOG_DIR,
    atomic_write_json,
    _replace_file_with_retry,
    classproperty,
    load_dotenv,
    AppConfig,
    app_config,
)
from .browser_constants import (
    BrowserConstants,
    _browser_constant_bool,
    _browser_constant_int,
    _BrowserConstantEnabledFilter,
)
from .exceptions import (
    BrowserError,
    BrowserConnectionError,
    ElementNotFoundError,
    WorkflowError,
    WorkflowCancelledError,
    ConfigurationError,
)
from .sse_formatter import SSEFormatter
from .message_validator import MessageValidator
from .log_collector import LogCollector, log_collector
from .log_redaction import (
    _SENSITIVE_KEY_HINTS,
    _REDACTED_TEXT,
    _redact_data_uri_for_log,
    _redact_long_base64_for_log,
    _BASE64_LOG_CHARS,
    _SENSITIVE_TEXT_SCAN_HINT_RE,
    _SENSITIVE_TEXT_PRECHECK_MIN_CHARS,
    _SENSITIVE_TEXT_LARGE_OMIT_THRESHOLD,
    _SENSITIVE_TEXT_LARGE_EDGE_CHARS,
    _has_long_base64_candidate,
    _redact_long_base64_runs_for_log,
    _should_scan_sensitive_text,
    _SENSITIVE_TEXT_PATTERNS,
    _SENSITIVE_BEARER_PATTERN,
    _SENSITIVE_STANDALONE_TOKEN_PATTERNS,
    _SENSITIVE_HEADER_PATTERN,
    _SENSITIVE_PARAM_PATTERNS,
    _sanitize_standalone_sensitive_tokens,
    _is_sensitive_key,
    _sanitize_sensitive_text,
    sanitize_sensitive_data,
)
from .log_formatters import (
    _truncate_long_message,
    _get_log_display_limit,
    _record_request_id,
    _REQUEST_SHORT_ID_PATTERN,
    _request_display_tag,
    _record_request_tag,
    _compact_logger_name_impl,
    _compact_logger_name,
    _LOGGER_DISPLAY_WIDTH,
    _record_logger_name,
    _record_kind,
    _LEVEL_BADGES,
    _record_level_badge,
    _replace_log_tag,
    _normalize_log_display_expression,
    _record_display_message,
    _format_log_display_parts,
    _join_log_display_parts,
    _format_log_display_line,
    _WebLogHandler,
    _web_log_handler,
    _enable_windows_ansi,
    _should_use_console_color,
    _ConsoleColorFormatter,
    _FileLogFormatter,
    _DisplayLogFormatter,
    _is_windows_file_lock_error,
    _SafeRotatingFileHandler,
    _get_positive_int_env,
    _resolve_log_dir,
    get_log_file_path,
    get_shared_file_log_handler,
    _shared_file_log_handler,
    _shared_file_log_handler_lock,
)
from .cute_translator import (
    _REQUEST_FINISH_PATTERN,
    _TAB_START_INDEX_PATTERN,
    _TAB_START_ROUTE_PATTERN,
    _CHUNKED_LONG_TEXT_PATTERN,
    _CHUNKED_DONE_PATTERN,
    _CHUNKED_SHORT_TEXT_PATTERN,
    _CHUNKED_FIRST_BLOCK_PATTERN,
    _CHUNKED_PROGRESS_PATTERN,
    _VERIFY_OK_EXACT_PATTERN,
    _SEND_SUCCESS_RETRY_PATTERN,
    _FILE_PASTE_DONE_PATTERN,
    _CLIPBOARD_OK_PATTERN,
    _FILE_PASTE_UPLOAD_SIGNAL_PATTERN,
    _FILE_PASTE_WEAK_SIGNAL_PATTERN,
    _FILE_PASTE_INPUT_SIGNAL_PATTERN,
    _FILE_PASTE_INPUT_UPLOADED_PATTERN,
    _FILE_PASTE_HINT_PATTERN,
    _FILE_PASTE_TEMP_FILE_PATTERN,
    _STEALTH_SEND_RETRY_PATTERN,
    _STEALTH_SEND_RETRY_SIMPLE_PATTERN,
    _STEALTH_WARMUP_DONE_PATTERN,
    _STEALTH_REVIEW_DELAY_PATTERN,
    _STEALTH_CLIPBOARD_PASTE_NOCLICK_PATTERN,
    _STEALTH_CLIPBOARD_PASTE_PATTERN,
    _STEALTH_RANDOM_PAUSE_PATTERN,
    _STEALTH_PRE_SEND_HESITATE_PATTERN,
    _STEALTH_HUMAN_CLICK_PATTERN,
    _SEND_ATTACHMENT_WAIT_PATTERN,
    _SEND_ATTACHMENT_READY_PATTERN,
    _SEND_ATTACHMENT_SETTLE_PATTERN,
    _SEND_RETRY_ACTION_PATTERN,
    _SEND_RETRY_WINDOW_PATTERN,
    _bool_phrase,
    _split_suppressed_suffix,
    _add_suppressed_marker,
    _restore_suppressed_hint,
    _apply_cute_rules,
    _cute_stage_title,
    _CUTE_EXTRA_RULES,
    _ERROR_KEYWORD_HINTS,
    _cuteify_error_message,
    _cuteify_info_message,
    _cuteify_warning_message,
    _cuteify_debug_message,
)
from .secure_logger import (
    _request_context,
    _command_log_context,
    _logger_setup_lock,
    _logger_registry_lock,
    _logger_registry,
    SecureLogger,
    command_log_context,
    get_logger,
    logger,
)

__all__ = [
    # 应用配置
    'AppConfig',
    'app_config',
    'load_dotenv',
    'PROJECT_ROOT',
    'DEFAULT_LOG_DIR',
    'atomic_write_json',
    '_replace_file_with_retry',
    'classproperty',

    # 浏览器常量
    'BrowserConstants',
    '_browser_constant_bool',
    '_browser_constant_int',
    '_BrowserConstantEnabledFilter',

    # 日志系统与收集器
    'SecureLogger',
    'logger',
    'get_logger',
    'log_collector',
    'LogCollector',
    '_request_context',
    '_command_log_context',
    'command_log_context',
    'get_log_file_path',
    'get_shared_file_log_handler',
    '_shared_file_log_handler',
    '_shared_file_log_handler_lock',
    '_logger_setup_lock',
    '_logger_registry_lock',
    '_logger_registry',
    'sanitize_sensitive_data',

    # 异常
    'BrowserError',
    'BrowserConnectionError',
    'ElementNotFoundError',
    'WorkflowError',
    'WorkflowCancelledError',
    'ConfigurationError',

    # SSE 与消息工具
    'SSEFormatter',
    'MessageValidator',
]
